#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

FILE="/var/run/holbertonscript.pid"
sudo touch $FILE
echo $$ > $FILE

trap "echo I hate the kill command && sudo rm $FILE && exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm $FILE && exit" SIGQUIT

for ((;;))
do
	echo "To infinity and beyond"
	sleep 2
done
