#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
while [ $i -lt 11 ]
do
	if [ $i -ne 4 ] && [ $i -ne 8 ]
	then
		echo "Holberton School"
	elif [ $i -eq 4 ]
	then
		echo "bad luck"
	else
		echo "good luck"
	fi
	((i++))
done
