#!/usr/bin/env bash
# Nginx config

pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod -R 700 /etc/nginx/
sudo -u nginx nginx -c /etc/nginx/nginx.conf
